name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - pip
  - jupyterlab>=3
  - ipywidgets
  - nodejs
  - nb_conda_kernels
  - tornado
  - widgetsnbextension
  - dask-labextension
  - jupyter-server-proxy
  - pip 